file = open("output.txt","w")
write_str=input("Enter text to write to the file: ")
file.write(write_str + "\n")
file.close()
print("Data successfully written to output.txt.")
print()
file2 = open("output.txt","a")
append_str= input("Enter additional text to append: ")
file2.write(append_str)
file2.close()
print("Data successfully appended.")
print()
print("Final content of output.txt:")
file3 = open("output.txt","r")
print(file3.read())
